### ISSUE TITLE
dropdown widget prevents shift-enter from working

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Interact.jl#31] opened 2014-08-27 14:24 UTC
doing `using Interact; dropdown(["one","two","three"])` in IJulia, and then changing the dropdown selection, seems to make IPython ignore shift-enter in subsequent cells; or rather it treats it just as "enter"  and inserts an ordinary newline in the cell.

(I can still run subsequent cells, but only by clicking the "run" button in the toolbar.

So, somehow the dropdown widget seems to be altering IPython's keybindings.  (@Carreau?)

**Comment by PBrockmann** [comment] 2015-01-16 14:57
I have just encountered the problem. Very annoying because you need to shutdown your notebook and restart it (the refresh does not solve the problem for me)
I can confirm that with
 * IPython 2.2.0 and firefox 34.0.5 
 * IPython 2.3.1 and firefox 35.0

once the dropdown widget has been used, there is no way to use anymore the shift-enter keys to run a cell. The only way left is to use the run icon.
Note that with google-chrome it works correctly.

Any idea ?

**Comment by shashi** [comment] 2015-07-01 02:39
Seems to be fixed on IPython 3.0

**Closed by shashi** 2015-07-01 02:39 UTC
